# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'E-Mail address', 'verbose_name_plural': 'E-Mail addresses'},
        ),
        migrations.AlterModelOptions(
            name='emailconfirmation',
            options={'verbose_name': 'E-Mail confirmation', 'verbose_name_plural': 'E-Mail confirmations'},
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailconfirmation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signupcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German')], default='', max_length=32, verbose_name='language'),
        ),
    ]
